/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciadeviajes;

import javax.swing.JOptionPane;

/**
 *
 * @author coste
 */
public class EjercicioTrece extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioTrece
     */
    public EjercicioTrece() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtD = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblC = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cmdB = new javax.swing.JButton();
        cmdR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de viajes");
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad de personas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPKeyTyped(evt);
            }
        });
        jPanel2.add(txtP, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 27, 60, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad de días", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtD.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDKeyTyped(evt);
            }
        });
        jPanel3.add(txtD, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 27, 60, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 60));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad a pagar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblC.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 140, 110));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdB.setText("Borrar");
        cmdB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBActionPerformed(evt);
            }
        });
        jPanel5.add(cmdB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        cmdR.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdR.setText("Resolver");
        cmdR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRActionPerformed(evt);
            }
        });
        jPanel5.add(cmdR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBActionPerformed
        // TODO add your handling code here:
        txtP.setText("");
        txtD.setText("");
        lblC.setText("");
        txtP.requestFocusInWindow();
    }//GEN-LAST:event_cmdBActionPerformed

    private void txtPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtPKeyTyped

    private void txtDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtDKeyTyped

    private void cmdRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRActionPerformed
        // TODO add your handling code here:
        String c;
        double d, p, m, s, l;
        lblC.setText("");
        if (txtD.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el número de días", "Error", JOptionPane.ERROR_MESSAGE);
            txtD.requestFocusInWindow();
        } else if (txtP.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el número de personas", "Error", JOptionPane.ERROR_MESSAGE);
            txtP.requestFocusInWindow();
        } else {
            p = Double.parseDouble(txtP.getText());
            d = Double.parseDouble(txtD.getText());
            if (p == 0) {
                JOptionPane.showMessageDialog(this, "No se puede colocar 0", "Error", JOptionPane.ERROR_MESSAGE);
                txtP.requestFocusInWindow();
            } else if (d == 0) {
                JOptionPane.showMessageDialog(this, "No se puede colocar 0", "Error", JOptionPane.ERROR_MESSAGE);
                txtD.requestFocusInWindow();
            } else {
                m = (p * d * 25000);
                s = (m * 12) / 100;
                l = m + s;
                c = String.valueOf(l);
                lblC.setText(" $ " + c);
            }
    }//GEN-LAST:event_cmdRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioTrece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioTrece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioTrece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioTrece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioTrece().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdB;
    private javax.swing.JButton cmdR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblC;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtP;
    // End of variables declaration//GEN-END:variables
}
